name: u2325
favicon: null
layout_spectrum: 0.7588680707849562
typography_spectrum: 0.9036199690308422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8813027699943632
  lightness: 0.28120304364711046
  saturation: 0.4116846174001694
  rhythmicContrast: 0.7459509964101017
purpose: []
